linters-settings:
  funlen:
    lines: 100
    statements: 50
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - rowserrcheck
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude:
    - "ST1000: at least one file in a package should have a package comment"