kafka:
  brokers: [ "localhost:29092" ]
  topic: "test-project"
  consumerGroup: "test-consumer-group"
producer:
  msgBatchSize: 100
  sortedMsgBatchSize: 200
  writeTimeOutSec: 1
  requireTimestampSort: true
database:
  DSN: "postgres://postgres:8Bm4e202@localhost:5432/test"
  createBatchSize: 1000
  createNewRows: true
performance:
  maxThreads: 8
  maxMessagesPerThread: 100000
  maxDeadThreads: 2
  maxDeadTimeOut: 30
consumer:
  readCommitIntervalSec: 1
  minReadBytes: 1000
  maxReadBytes: 10000000
tarantool:
  user: "admin"
  password: "password"
  host: "localhost:3301"
  batchSize: 500
  space: "messages"
dumps:
  dumpDir: "./dumps/"
  maxDumpSize: 16
  maxBufSize: 10000
logging:
  producerLogPath: "./writer_log.txt"
  consumerLogPath: "./reader_log.txt"
  dbLogPath: "./db_log.txt"
  logLevel: "debug"