kafka: "localhost:9092"
kafkaTopic: "test-project"
kafkaConsumerGroup: "test-consumer-group"
readCommitInterval: 1
maxThreads: 4
maxMessagesPerThread: 100000
msgBatchSize: 10
dumpDir: "./dumps/"
maxDumpSize: 16
maxBufSize: 1000
maxDeadThreads: 2
maxDeadTimeOut: 30
minReadBytes: 1000
maxReadBytes: 10000000
writerLogPath: "./writer_log.txt"
readerLogPath: "./reader_log.txt"
logLevel: "debug"