kafka: "localhost:9092"
kafkaTopic: "test-project"
kafkaPartition: 0
maxThreads: 4
maxMessagesPerThread: 40000
dumpFile: "./dump.txt"
maxBufSize: 1000
maxDeadThreads: 2
maxDeadTimeOut: 30
logPath: "./log.txt"
logLevel: "info"