kafka:
  brokers: ["localhost:29092"]
  topic: "test-project"
  consumerGroup: "test-consumer-group"
producer:
  msgBatchSize: 10
  writeTimeOutSec: 1
database:
  DSN: "postgres://postgres:example@localhost:5432"
performance:
  maxThreads: 4
  maxMessagesPerThread: 100000
  maxDeadThreads: 2
  maxDeadTimeOut: 30
consumer:
  readCommitIntervalSec: 1
  minReadBytes: 1000
  maxReadBytes: 10000000
dumps:
  dumpDir: "./dumps/"
  maxDumpSize: 16
  maxBufSize: 10000
logging:
  producerLogPath: "./writer_log.txt"
  consumerLogPath: "./reader_log.txt"
  dbLogPath: "./db_log.txt"
  logLevel: "debug"