version: '2'

services:
  tarantool1:
    image: tarantool/tarantool:2.11
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "password"
    networks:
      - mynet
    ports:
      - "3301:3301"

  tarantool2:
    image: tarantool/tarantool:2.11
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "password"
    networks:
      - mynet
    ports:
      - "3302:3301"

networks:
  mynet:
    driver: bridge
